---

- name: Instala mariadb
  yum:
    name: mariadb-server
    state: present

- name: Servicio MariaDB arrancado y activado
  service:
    name: mysql
    state: started
    enabled: true

- name: Abre firewall para MariaDB
  firewalld:
    service: mysql
    state: enabled
    permanent: yes
    immediate: yes

