---            
- name: Copia backup logico world.dump    
  copy:        
    src: files/world.dump
    dest: /tmp/world.dump

- name: Recupera backup
  shell: mysql -u root -predhat < /tmp/world.dump

- name: Borra backup logico world.dump
  file:
    path: /tmp/world.dump
    state: absent


