---
- name: Copia script secure.sql
  copy:
    dest: /tmp/secure.sql
    src: files/secure.sql

- name: Ejecuta securizacion
  shell: mysql -u root < /tmp/secure.sql
  ignore_errors: yes

- name: Elimina script secure.sql
  file:
    path: /tmp/secure.sql
    state: absent
