---
# tasks file for sample-apache

- name: Instala httpd, modulo mod_ssl y modulo php
  yum:
    name:
      - httpd
      - mod_ssl
      - php
    state: present


- name: Inicializa servicio httpd y se configura para arrancar automaticamente on boot
  service:
    name: httpd
    state: started
    enabled: yes


- name: Abre puerto en el firewall
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop:
    - http
    - https


- name: Genera fichero index.html
  template:
    dest: /var/www/html/index.html
    src: index.html.j2
    owner: apache
    group: apache
  notify: reinicia httpd

      
