---        
- name: Elimina Nginx
  hosts: webservers
  tasks:   
    - name: Parada y desactivacion Nginx
      service:
        name: nginx
        state: stopped
        enabled: no
           
    - name: Elimina index.html
      file:
        path: /usr/share/nginx/html/index.html
        state: absent
           
    - name: Desinstala Nginx
      yum: 
        name: nginx
        state: absent
           
- name: Elimina Apache
  hosts: webservers
  tasks:   
    - name: parada y desactiva servicio httpd
      service:
        name: httpd
        enabled: no
        state: stopped
           
    - name: Desinstala Apache
      yum: 
        name: httpd
        state: absent

