---
- name: despliega Nginx
  hosts: webservers
  tasks:
    - name: Instala Nginx
      yum:
        name: nginx
        state: present

    - name: Crear index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "Bienvenido a la web de Walter Nginx"
        owner: nginx
        mode: 0644

    - name: Arranque y activacion Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Abre firewall
      firewalld:
        permanent: yes
        immediate: yes
        state: enabled
        service: http


- name: Despliega NFS-server
  hosts: webservers
  tasks:   
    - name: Despliega NFS-server  
      yum: 
        name: nfs-utils
        state: present

    - name: Crea directorio /exports
      file:
        path: /exports
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Crea recurso a exportar
      file:
        path: /exports/Asir2-Walter
        state: directory
        mode: '0755'
        owner: automation
        group: automation

    - name: Exporta recurso
      copy:
        dest: /etc/exports.d/proyecto.exports
        content: "/exports/Asir2-Walter *(sync)"


    - name: Arranca y activa servicio NFS-server
      service:
        name: nfs-server
        enabled: yes
        state: restarted



- name: Cliente NFS y testeo del apache
  hosts: localhost
  tasks:   
    - name: Crear directorio /exports
      file:
        path: /proyectoFinal
        state: directory
    
    - name: montar recurso remoto
      mount:
        fstype: nfs
        path: /proyectoFinal
        src: server1.lab.example.com:/exports/Asir2-Walter
        state: mounted
      ignore_errors: true

    - name: testeo del apache
      uri: 
        url: http://server1.lab.example.com
        return_content: yes
        status_code: 200
