---
- name: Respositorio de software
  hosts: database
  tasks:
    - name: Crea repositorio
      yum_repository:
        file: mysql56-community
        name: mysql56-community
        description: MySQL 5.6 YUM Repo
        baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
        enabled: yes
        gpgcheck: no
        state: present

