---
# vars file for sample-mysql
partition:
  number: 1
  device: /dev/sdb
  start: 1MiB
  end: 800MiB

volume_group:
  name: vg_database
  device: /dev/sdb1

logical_volume:
  name: lv_mysql
  size: 512m
  vgroup: vg_database
  mount_path: /mnt/mysql_backups
  type: xfs

firewalld:
  port: 3306
